export const APIConstant = {
    AUTH:{
        LOGIN:"/Auth/login",
        REFRESH_TOKEN:"/Auth/refresh-token",
        REGISTER:"/Auth/register",
        FORGOT_PASSWORD:"/Auth/forgot-password",
        CHANGE_USER_PASSWORD:"/Auth/user-password"
    },
    IMAGES:{
        UPLOAD:"/Image/upload"
    },
    USERS:{
        GET_ALL:"/Users",
        GET_BY_ID:"/Users",
        ADD:"/Users",
        UPDATE:"/Users",
        DELETE:"/Users"
    },
    USERGROUP:{
        GET_ALL:"/user-groups/getall",
        GET_BY_ID:"/user-groups/getbyid",
        ADD:"/user-groups",
        UPDATE:"/user-groups",
        DELETE:"/user-groups"
    },
    GROUP:{
        GET_ALL:"/Groups",
        GET_BY_ID:"/Groups",
        ADD:"/Groups",
        UPDATE:"/Groups",
        DELETE:"/Groups"
    },    
    ADDRESSES:{
        GET_ALL:"/Addresses/getall",
        GET_BY_ID:"/Addresses/getbyid",
        ADD:"/Addresses",
        UPDATE:"/Addresses",
        DELETE:"/Addresses"
    },
    COLORS:{
        GET_ALL:"/Colors/getall",
        GET_BY_ID:"/Colors/getbyid",
        ADD:"/Colors",
        UPDATE:"/Colors",
        DELETE:"/Colors"
    },
    CITIES:{
        GET_ALL:"/Cities/getall",
        GET_BY_ID:"/Cities/getbyid",
        ADD:"/Cities",
        UPDATE:"/Cities",
        DELETE:"/Cities"
    },
    COUNTRIES:{
        GET_ALL:"/Countries/getall",
        GET_BY_ID:"/Countries/getbyid",
        ADD:"/Countries",
        UPDATE:"/Countries",
        DELETE:"/Countries"
    },
    CATEGORIES:{
        GET_ALL:"/Categories/getall",
        GET_BY_ID:"/Categories/getbyid",
        ADD:"/Categories",
        UPDATE:"/Categories",
        DELETE:"/Categories"
    },
    PRODUCTORDERS:{
        GET_ALL:"/ProductOrders/getall",
        GET_BY_ID:"/ProductOrders/getbyid",
        ADD:"/ProductOrders",
        UPDATE:"/ProductOrders",
        DELETE:"/ProductOrders"
    },
    PRODUCTS:{
        GET_ALL:"/Products/getall",
        GET_ALL_PAGINATION:"/Products/getall-page",
        GET_ALL_FOR_STORAGE:"/Products/getall-storage",
        GET_BY_ID:"/Products/getbyid",
        ADD:"/Products",
        UPDATE:"/Products",
        DELETE:"/Products"
    },
    ORDERS:{
        GET_ALL:"/Orders/getall",
        GET_ALL_FOR_CUSTOMER:'/Orders/getall-customer',
        GET_BY_ID:"/Orders/getbyid",
        ADD:"/Orders",
        UPDATE:"/Orders",
        DELETE:"/Orders"
    },
    CUSTOMERS:{
        GET_ALL:"/Customers/getall",
        GET_BY_ID:"/Customers/getbyid",
        ADD:"/Customers",
        UPDATE:"/Customers",
        DELETE:"/Customers"
    },
    STORAGES:{
        GET_ALL:"/Storages/getall",
        GET_BY_ID:"/Storages/getbyid",
        ADD:"/Storages",
        UPDATE:"/Storages",
        DELETE:"/Storages"
    },
    DASHBOARD:{
        GET_DATA:"/Dashboard/get-data"
    }
}